# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoragePicturesWithPasswordApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'SwiftyKeychainKit', '1.0.0-beta.2'
  # Pods for StoragePicturesWithPasswordApp

end
